import {
  Activity,
  BarChart3,
  BellRing,
  Blocks,
  BookOpen,
  Bot,
  BotMessageSquare,
  Boxes,
  Briefcase,
  Bug,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Coins,
  DollarSign,
  FileCheck2,
  FileSignature,
  FileText,
  FolderOpen,
  Gauge,
  GraduationCap,
  Handshake,
  History,
  IdCard,
  KeyRound,
  LayoutTemplate,
  Lightbulb,
  Link2,
  ListChecks,
  Mail,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  NotebookPen,
  QrCode,
  PenTool,
  Receipt,
  ScanBarcode,
  Send,
  ShieldCheck,
  Star,
  ShoppingBag,
  Ticket,
  Timer,
  UserCog,
  UtensilsCrossed,
  Workflow,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

/**
 * Manifestteki `ikon` adı → lucide bileşeni.
 *
 * Bütün lucide paketini içe almamak için yalnız manifestte geçen adlar
 * burada; bilinmeyen ad `Blocks` ile çiziliyor. Manifeste yeni ikon eklenirse
 * buraya da eklenmeli (arka uç testi manifest ikonlarını bu dosyada arıyor).
 */
export const MODUL_IKONLARI: Record<string, LucideIcon> = {
  Activity,
  BarChart3,
  BellRing,
  Blocks,
  BookOpen,
  Bot,
  BotMessageSquare,
  Boxes,
  Briefcase,
  Bug,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Coins,
  DollarSign,
  FileCheck2,
  FileSignature,
  FileText,
  FolderOpen,
  Gauge,
  GraduationCap,
  Handshake,
  History,
  IdCard,
  KeyRound,
  LayoutTemplate,
  Lightbulb,
  Link2,
  ListChecks,
  Mail,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  NotebookPen,
  QrCode,
  PenTool,
  Receipt,
  ScanBarcode,
  Send,
  ShieldCheck,
  Star,
  ShoppingBag,
  Ticket,
  Timer,
  UserCog,
  UtensilsCrossed,
  Workflow,
  Wrench,
};

export function modulIkonu(ad?: string | null): LucideIcon {
  return (ad && MODUL_IKONLARI[ad]) || Blocks;
}
