"""auto update

Revision ID: a52336dc1593
Revises: f48bc22d62d0
Create Date: 2026-09-05 08:46:05.607274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52336dc1593'
down_revision: Union[str, Sequence[str], None] = 'f48bc22d62d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_column('invoices', 'user_id')
    op.add_column('support_tickets', sa.Column('client_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_column('support_tickets', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.drop_column('support_tickets', 'client_name')
    op.add_column('invoices', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    # ### end Alembic commands ###